### ISSUE TITLE
Replace "Barwoman"

### ISSUE THREAD

**Issue by varholak-peter** [amwmedia/eslint-plugin-woke#1]
The `gender` categories includes the word "barwoman" which is a word nobody really uses.

As such I propose either replacing it with the word `'barmaid'` or adding that to the list in addition to current list.

[List in question](https://github.com/amwmedia/eslint-plugin-woke/blob/master/lib/categories/gender.js#L8)

**Comment by amwmedia** [comment]
Sounds good to me.

**Comment by amwmedia** [comment]
Added, it'll be in the next release
