### ISSUE TITLE
This plugin is missing the point.

### ISSUE THREAD

**Issue by Uzlopak** [amwmedia/eslint-plugin-woke#4]
I was just curious about this plugin as i am not a fan of woke culture. I read the source code and I think this plugin is missing the point. Yeah wow, I can not use the word {insert slur here} in my code. And so what if I write in my source code comments "// TODO: what the fuck". Maybe not professional to write that but still... 

Despite that I am not a fan of woke culture, I think somebody installing this plugin would expect to get help for having better wording for TECHNICAL terminology. Naming of technical terms/variables/classes/etc. is the most discussed issue in professional programming. So helping to speed up the technical discussion would help in a lot of cases.

Technical Terminology as e.g. master and slave could be replaced by primary and secondary. Or not slaves but replicas. 
Or blacklist and whitelist could be replaced by passlist and blocklist. Or that thing with sanity check (was that the woke replacement? or was this the no-no-Word for validity?).

E.g. you start writing a program, and then you think "Oh I need a blacklist". You type blacklist run your linters, and *boom* "blacklist is a no-no-word, change it with blocklist". So you say: "Hey that is actually also a very good word for this variable/class/etc.. I am at the beginning of my project, so there is a low effort to rename this. I replace the word ." Scandal averted as the woke wont complain. 

Now you have just the patronizing "Hey the word blacklist is considered a no-no-word" but no suggestion what an appropriate replacement could be. 

So yeah... I recommend to extend this plugin to have some real life use with recommending a potential replacement. Nobody serious would write racial slurs into his code (well except for this plugin i guess), or stuff like barmaid (use case?) but alot of people use still blacklist, master-branch, etc.. Pointing to technical alternatives would be alot of help, even if you arent a fan of woke culture.

**Comment by amwmedia** [comment]
Yeah, I agree. I originally wanted to make this plugin auto-suggest replacements or even use the `autofix` feature but soon realized that there's no good way (that I could think of) to offer reasonable replacements for every slur, curse, and offensive word.

**Comment by Uzlopak** [comment]
I recommend to you to remove all the curse, slurs, and offensive words from this package. I mean, you only cover english words but not german, french etc..

Even gender neutrality makes no sense if it is not in a technical context.  Imagine a program makes you to select your gender, man, woman, or diverse... your script says this is not genderneutral. Makes no sense, even though the implementor did the right think. 

I recommend to you to focus on the technical terms.

**Comment by amwmedia** [comment]
The plugin can be configured to exclude any of the different sections, why totally remove them? Also, if you know any German or French slurs, I'd be happy to accept a PR.

**Comment by Uzlopak** [comment]
I am not convinced of the usefulness of this plugin. Adding German slurs makes no sense. In Germany it could also be considered an insult if the word is not insulting and being branded as insulting. A former employer of mine even removed their insultlist to avoid legal issues.

Well yeah anyway. I think I made my point
