### ISSUE TITLE
Add support for eslint 8

### ISSUE THREAD

**Issue by AKK9** [amwmedia/eslint-plugin-woke#5]
Is it possible to add support for eslint 8?

**Comment by amwmedia** [comment]
I haven't looked into what is needed for this, but I'd be open to a PR for sure.

**Comment by amwmedia** [comment]
@AKK9 I think PR #6 has all that's needed. Thoughts?

**Comment by AKK9** [comment]
Current latest version does work fine with eslint 7, it's just the incorrect peer deps warning that I noticed, so this looks good to me. 👍

Thanks for doing this
