### ISSUE TITLE
Question about a term for Russians

### ISSUE THREAD

**Issue by VlaDexa** [amwmedia/eslint-plugin-woke#7]
Why exactly is word "russkie" is banned?

**Comment by VlaDexa** [comment]
Russian people called "Русские" in Russian which sounds exactly like "russkie".
Source: I am Russian

**Comment by amwmedia** [comment]
It was listed in a Wikipedia page of ethnic slurs

**Comment by VlaDexa** [comment]
Understandable, have a nice day
